name: iMessage backend deploy

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build and push
      run: |
        echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u "begninix" --password-stdin
        docker image build -t begninix/ezops-frontend:master .
        docker push begninix/ezops-frontend:master
