name: iMessage backend deploy

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build and push
      run: |
        echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u "begninix" --password-stdin
        docker image build -t begninix/ezops-backend:master .
        docker push begninix/ezops-backend:master
    - uses: appleboy/ssh-action@master
    - name: recreate containers
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: docker-compose pull && docker-compose up -d
